<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BusinessQuestionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'commercialization.q1' => ['required', 'boolean'],
            'commercialization.q2' => ['required', 'boolean'],
            'commercialization.q3' => ['required', 'boolean'],
            'commercialization.q4' => ['required', 'boolean'],
            'commercialization.q5' => ['required', 'boolean'],
            'commercialization.q6' => ['required', 'boolean'],
            'commercialization.q7' => ['required', 'boolean'],
            'commercialization.q8' => ['required', 'boolean'],
            'commercialization.q9' => ['required', 'boolean'],
            'commercialization.q10' => ['required', 'boolean'],
            'public_management.q1' => ['required', 'boolean'],
            'public_management.q2' => ['required', 'boolean'],
            'public_management.q3' => ['required', 'boolean'],
            'public_management.q4' => ['required', 'boolean'],
            'public_management.q5' => ['required', 'boolean'],
            'public_management.q6' => ['required', 'boolean'],
            'public_management.q7' => ['required', 'boolean'],
            'public_management.q8' => ['required', 'boolean'],
            'public_management.q9' => ['required', 'boolean'],
            'public_management.q10' => ['required', 'boolean'],
            'functional_management.q1' => ['required', 'boolean'],
            'functional_management.q2' => ['required', 'boolean'],
            'functional_management.q3' => ['required', 'boolean'],
            'functional_management.q4' => ['required', 'boolean'],
            'functional_management.q5' => ['required', 'boolean'],
            'functional_management.q6' => ['required', 'boolean'],
            'functional_management.q7' => ['required', 'boolean'],
            'functional_management.q8' => ['required', 'boolean'],
            'functional_management.q9' => ['required', 'boolean'],
            'functional_management.q10' => ['required', 'boolean'],
            'sale_and_technical_support.q1' => ['required', 'boolean'],
            'sale_and_technical_support.q2' => ['required', 'boolean'],
            'sale_and_technical_support.q3' => ['required', 'boolean'],
            'sale_and_technical_support.q4' => ['required', 'boolean'],
            'sale_and_technical_support.q5' => ['required', 'boolean'],
            'sale_and_technical_support.q6' => ['required', 'boolean'],
            'sale_and_technical_support.q7' => ['required', 'boolean'],
            'sale_and_technical_support.q8' => ['required', 'boolean'],
            'sale_and_technical_support.q9' => ['required', 'boolean'],
            'sale_and_technical_support.q10' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q1' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q2' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q3' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q4' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q5' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q6' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q7' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q8' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q9' => ['required', 'boolean'],
            'liquidity_and_access_to_capital.q10' => ['required', 'boolean'],
            'competitive_position.q1' => ['required', 'boolean'],
            'competitive_position.q2' => ['required', 'boolean'],
            'competitive_position.q3' => ['required', 'boolean'],
            'competitive_position.q4' => ['required', 'boolean'],
            'competitive_position.q5' => ['required', 'boolean'],
            'competitive_position.q6' => ['required', 'boolean'],
            'competitive_position.q7' => ['required', 'boolean'],
            'competitive_position.q8' => ['required', 'boolean'],
            'competitive_position.q9' => ['required', 'boolean'],
            'competitive_position.q10' => ['required', 'boolean'],
            'customer_recognition.q1' => ['required', 'boolean'],
            'customer_recognition.q2' => ['required', 'boolean'],
            'customer_recognition.q3' => ['required', 'boolean'],
            'customer_recognition.q4' => ['required', 'boolean'],
            'customer_recognition.q5' => ['required', 'boolean'],
            'customer_recognition.q6' => ['required', 'boolean'],
            'customer_recognition.q7' => ['required', 'boolean'],
            'customer_recognition.q8' => ['required', 'boolean'],
            'customer_recognition.q9' => ['required', 'boolean'],
            'customer_recognition.q10' => ['required', 'boolean'],
            'customer_commitment.q1' => ['required', 'boolean'],
            'customer_commitment.q2' => ['required', 'boolean'],
            'customer_commitment.q3' => ['required', 'boolean'],
            'customer_commitment.q4' => ['required', 'boolean'],
            'customer_commitment.q5' => ['required', 'boolean'],
            'customer_commitment.q6' => ['required', 'boolean'],
            'customer_commitment.q7' => ['required', 'boolean'],
            'customer_commitment.q8' => ['required', 'boolean'],
            'customer_commitment.q9' => ['required', 'boolean'],
            'customer_commitment.q10' => ['required', 'boolean'],
            'affordable.q1' => ['required', 'boolean'],
            'affordable.q2' => ['required', 'boolean'],
            'affordable.q3' => ['required', 'boolean'],
            'affordable.q4' => ['required', 'boolean'],
            'affordable.q5' => ['required', 'boolean'],
            'affordable.q6' => ['required', 'boolean'],
            'affordable.q7' => ['required', 'boolean'],
            'affordable.q8' => ['required', 'boolean'],
            'affordable.q9' => ['required', 'boolean'],
            'affordable.q10' => ['required', 'boolean'],
            'intellectual_property_management.q1' => ['required', 'boolean'],
            'intellectual_property_management.q2' => ['required', 'boolean'],
            'intellectual_property_management.q3' => ['required', 'boolean'],
            'intellectual_property_management.q4' => ['required', 'boolean'],
            'intellectual_property_management.q5' => ['required', 'boolean'],
            'intellectual_property_management.q6' => ['required', 'boolean'],
            'intellectual_property_management.q7' => ['required', 'boolean'],
            'intellectual_property_management.q8' => ['required', 'boolean'],
            'intellectual_property_management.q9' => ['required', 'boolean'],
            'intellectual_property_management.q10' => ['required', 'boolean'],
            'sale_forecast.q1' => ['required', 'boolean'],
            'sale_forecast.q2' => ['required', 'boolean'],
            'sale_forecast.q3' => ['required', 'boolean'],
            'sale_forecast.q4' => ['required', 'boolean'],
            'sale_forecast.q5' => ['required', 'boolean'],
            'sale_forecast.q6' => ['required', 'boolean'],
            'sale_forecast.q7' => ['required', 'boolean'],
            'sale_forecast.q8' => ['required', 'boolean'],
            'sale_forecast.q9' => ['required', 'boolean'],
            'sale_forecast.q10' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q1' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q2' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q3' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q4' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q5' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q6' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q7' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q8' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q9' => ['required', 'boolean'],
            'uncertainty_prediction_questions.q10' => ['required', 'boolean'],
            'supply_chain.q1' => ['required', 'boolean'],
            'supply_chain.q2' => ['required', 'boolean'],
            'supply_chain.q3' => ['required', 'boolean'],
            'supply_chain.q4' => ['required', 'boolean'],
            'supply_chain.q5' => ['required', 'boolean'],
            'supply_chain.q6' => ['required', 'boolean'],
            'supply_chain.q7' => ['required', 'boolean'],
            'supply_chain.q8' => ['required', 'boolean'],
            'supply_chain.q9' => ['required', 'boolean'],
            'supply_chain.q10' => ['required', 'boolean'],
            'rule.q1' => ['required', 'boolean'],
            'rule.q2' => ['required', 'boolean'],
            'rule.q3' => ['required', 'boolean'],
            'rule.q4' => ['required', 'boolean'],
            'rule.q5' => ['required', 'boolean'],
            'rule.q6' => ['required', 'boolean'],
            'rule.q7' => ['required', 'boolean'],
            'rule.q8' => ['required', 'boolean'],
            'rule.q9' => ['required', 'boolean'],
            'rule.q10' => ['required', 'boolean'],
        ];
    }
}
