<?php

use App\Http\Controllers\user\BusinessCanvas\BusinessCanvasController;
use App\Http\Controllers\user\Description\Managerial\ManagerialController;
use App\Http\Controllers\user\Description\Managerial\ObtainedCertificateController;
use App\Http\Controllers\user\Description\Managerial\PlanImplementationController;
use App\Http\Controllers\user\Description\Market\AlternativeProductController;
use App\Http\Controllers\user\Description\Market\DesMarketController;
use App\Http\Controllers\user\Description\Market\EnvironmentalEffectController;
use App\Http\Controllers\user\Description\Market\OpportunityPointController;
use App\Http\Controllers\user\Description\Market\ProducerController;
use App\Http\Controllers\user\Description\Market\ProductCompetitorController;
use App\Http\Controllers\user\Description\Market\ProductCustomerController;
use App\Http\Controllers\user\Description\Market\ProductSupplyAndDemandController;
use App\Http\Controllers\user\Description\Market\RawMaterialSupplierController;
use App\Http\Controllers\user\Description\Market\RetailController;
use App\Http\Controllers\user\Description\Market\StrengthController;
use App\Http\Controllers\user\Description\Market\SupplierController;
use App\Http\Controllers\user\Description\Market\ThreatController;
use App\Http\Controllers\user\Description\Market\WeakPointController;
use App\Http\Controllers\user\Description\Technical\RequiredCertificateController;
use App\Http\Controllers\user\Description\Technical\TechnicalController;
use App\Http\Controllers\user\Financial\Financial1\BasicInformationController;
//use App\Http\Controllers\user\Financial\Financial1\BuildingController;
use App\Http\Controllers\user\Financial\Financial1\EquipmentAndMachineryController;
use App\Http\Controllers\user\Financial\Financial1\FacilityController;
use App\Http\Controllers\user\Financial\Financial1\Financial1Controller;
use App\Http\Controllers\user\Financial\Financial1\IndexController;
use App\Http\Controllers\user\Financial\Financial1\LaboratoryEquipmentController;
use App\Http\Controllers\user\Financial\Financial1\LandController;
use App\Http\Controllers\user\Financial\Financial1\OfficeEquipmentAndSupplyController;
use App\Http\Controllers\user\Financial\Financial1\PreOperatingCostController;
use App\Http\Controllers\user\Financial\Financial1\TransportationController;
use App\Http\Controllers\user\Financial\Financial2\AfterSaleServiceController;
use App\Http\Controllers\user\Financial\Financial2\BusinessController;
use App\Http\Controllers\user\Financial\Financial2\CapacityController;
use App\Http\Controllers\user\Financial\Financial2\ConsumerItemController;
use App\Http\Controllers\user\Financial\Financial2\DevelopmentCostController;
use App\Http\Controllers\user\Financial\Financial2\EnergyConsumptionController;
use App\Http\Controllers\user\Financial\Financial2\Financial2Controller;
use App\Http\Controllers\user\Financial\Financial2\InsuranceController;
use App\Http\Controllers\user\Financial\Financial2\ManPowerController;
use App\Http\Controllers\user\Financial\Financial2\OtherInformationController;
use App\Http\Controllers\user\Financial\Financial2\OutsourcingController;
use App\Http\Controllers\user\Financial\Financial2\RawMaterialController;
use App\Http\Controllers\user\Financial\Financial2\RDController;
use App\Http\Controllers\user\Financial\Financial2\RentController;
use App\Http\Controllers\user\Financial\Financial2\RepairController;
use App\Http\Controllers\user\Financial\Financial2\TransportationCostController;
use App\Http\Controllers\user\Financial\Financial2\WarrantyController;
use App\Http\Controllers\user\Justificationplan\JustificationPlanController;
use App\Http\Controllers\user\other\ProductController;
use App\Http\Controllers\user\other\TeamController;
use App\Http\Controllers\user\Readiness\ManufacturingController;
use App\Http\Controllers\user\Readiness\MarketController;
use App\Http\Controllers\user\Readiness\TechnologyController;
use App\Http\Controllers\user\Reporting\RepJustificationPlanController;
use App\Http\Controllers\user\Share\InitialShare\AgreementController;
use App\Http\Controllers\user\Share\InitialShare\CalculationController;
use App\Http\Controllers\user\Share\InitialShare\InitialShareController;
use App\Http\Controllers\user\Share\InitialShare\PreviousInvestorController;
use App\Http\Controllers\user\Share\InitialShare\ShareQuestionController;
use App\Http\Controllers\user\Share\InitialShare\ShareVariableController;
use App\Http\Controllers\user\Share\ParticipationShare\NewInvestorController;
use App\Http\Controllers\user\Share\ParticipationShare\ParticipationShareController;
use App\Http\Controllers\user\Share\ParticipationShare\PreInvestorController;
use App\Http\Controllers\user\TeamMember\KeyEmployeeController;
use App\Http\Controllers\user\TeamMember\ShareholderController;
use App\Http\Controllers\user\Valuation\Cost\CostController;
use App\Http\Controllers\user\Valuation\Intangible\IntangibleController;
use App\Http\Controllers\user\Valuation\Tangible\TangibleController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' =>['auth', 'auth.user']] , function (){
    Route::get('/user/dashboard', function (){
        return view('user.master');
    });

    Route::resource('/shareholders',ShareholderController::class);
    Route::resource('/key-employees', KeyEmployeeController::class);

    Route::resource('/team', TeamController::class);
    Route::resource('/products', ProductController::class);

    Route::get('/initial-shares',InitialShareController::class)->name('initial');
    Route::resource('/agreements', AgreementController::class);
    Route::get('/calculations', [CalculationController::class, 'index'])->name('calculations.index');
    Route::get('/calculations/create', [CalculationController::class, 'create'])->name('calculations.create');
    Route::post('/calculations', [CalculationController::class, 'store'])->name('calculations.store');
    Route::resource('/previousinvestors', PreviousInvestorController::class);
    Route::resource('/sharevariables', ShareVariableController::class);
    Route::resource('/sharequestions', ShareQuestionController::class);
    Route::resource('/participation-shares', ParticipationShareController::class);
    Route::resource('/pre-investors', PreInvestorController::class);
    Route::resource('/new-investors', NewInvestorController::class);

    Route::resource('/financial1', Financial1Controller::class);
    Route::resource('/basic-information', BasicInformationController::class);
    Route::resource('/lands', LandController::class);
//    Route::resource('/buildings', BuildingController::class);
    Route::resource('/laboratory-equipments', LaboratoryEquipmentController::class);
    Route::resource('/equipmentandmachineries', EquipmentAndMachineryController::class);
    Route::resource('/officeequipmentandsupplies', OfficeEquipmentAndSupplyController::class);
    Route::resource('/facilities', FacilityController::class);
    Route::resource('/transportations', TransportationController::class);
    Route::resource('/preoperatingcosts', PreOperatingCostController::class);

    Route::get('/financial2', [Financial2Controller::class,'index']);
    Route::get('/financial2/year/{id}', [Financial2Controller::class,'show']);
    Route::get('/financial2/year/{id}/create', [Financial2Controller::class,'create']);
    Route::post('/financial2/year/{id}', [Financial2Controller::class,'store']);
    Route::resource('/developmentcosts', DevelopmentCostController::class);
//    Route::get('/developmentcosts/{year}/create', [DevelopmentCostController::class, 'create']);
    Route::resource('/capacities', CapacityController::class);
    Route::resource('/rawmaterials', RawMaterialController::class);
    Route::get('/rawmaterials/{year}/create', [RawMaterialController::class, 'create']);
    Route::resource('/manpowers', ManPowerController::class);
    Route::get('/manpowers/{year}/create', [ManPowerController::class, 'create']);
    Route::resource('/rents', RentController::class);
    Route::get('/rents/{year}/create', [RentController::class, 'create']);
    Route::resource('/energyconsumptions', EnergyConsumptionController::class);
    Route::get('/energyconsumptions/{year}/create', [EnergyConsumptionController::class, 'create']);
    Route::resource('/rds', RDController::class);
    Route::get('/rds/{year}/create', [RDController::class, 'create']);
    Route::resource('/businesses', BusinessController::class);
    Route::get('/businesses/{year}/create', [BusinessController::class, 'create']);
    Route::resource('/insurances', InsuranceController::class);
    Route::get('/insurances/{year}/create', [InsuranceController::class, 'create']);
    Route::resource('/repairs', RepairController::class);
    Route::get('/repairs/{year}/create', [RepairController::class, 'create']);
    Route::resource('/transportationcosts', TransportationCostController::class);
    Route::get('/transportationcosts/{year}/create', [TransportationCostController::class, 'create']);
    Route::resource('/warranties', WarrantyController::class);
    Route::get('/warranties/{year}/create', [WarrantyController::class, 'create']);
    Route::resource('/consumeritems', ConsumerItemController::class);
    Route::get('/consumeritems/{year}/create', [ConsumerItemController::class, 'create']);
    Route::resource('/aftersaleservices', AfterSaleServiceController::class);
    Route::get('/aftersaleservices/{year}/create', [AfterSaleServiceController::class, 'create']);
    Route::resource('/outsourcings', OutsourcingController::class);
    Route::get('/outsourcings/{year}/create', [OutsourcingController::class, 'create']);
    Route::resource('/otherinformations', OtherInformationController::class);

    Route::resource('/justificationplan', JustificationPlanController::class);

    Route::resource('/businesscanvas', BusinessCanvasController::class);

    Route::resource('/valuation-costs', CostController::class);
    Route::resource('/valuation-tangible', TangibleController::class);
    Route::resource('/val-equipment-and-machineries', \App\Http\Controllers\user\Valuation\Tangible\EquipmentAndMachineryController::class);
    Route::resource('/val-facilities', \App\Http\Controllers\user\Valuation\Tangible\FacilityController::class);
    Route::resource('/val-laboratory-equipments', \App\Http\Controllers\user\Valuation\Tangible\LaboratoryEquipmentController::class);
    Route::resource('/val-office-supplies', \App\Http\Controllers\user\Valuation\Tangible\OfficeEquipmentAndSupplyController::class);
    Route::resource('/val-pre-operating-costs', \App\Http\Controllers\user\Valuation\Tangible\PreOperatingCostController::class);
    Route::resource('/val-tenements', \App\Http\Controllers\user\Valuation\Tangible\TenementController::class);
    Route::resource('/val-transportations', \App\Http\Controllers\user\Valuation\Tangible\TransportationController::class);
    Route::resource('/valuation-intangible', IntangibleController::class);

    Route::resource('/technology-questions', TechnologyController::class);
    Route::resource('/manufacturing-questions', ManufacturingController::class);
    Route::resource('/market-questions', MarketController::class);
    Route::resource('/business-questions', \App\Http\Controllers\user\Readiness\BusinessController::class);
    Route::resource('/commercialization-questions', \App\Http\Controllers\user\Readiness\CommercializationController::class);
    Route::resource('/publicmanagement-questions', \App\Http\Controllers\user\Readiness\PublicManagementController::class);
    Route::resource('/functionalmanagement-questions', \App\Http\Controllers\user\Readiness\FunctionalManagementController::class);
    Route::resource('/SaleAndTechnicalSupport-questions', \App\Http\Controllers\user\Readiness\SaleAndTechnicalSupportController::class);
    Route::resource('/LiquidityAndAccess-questions', \App\Http\Controllers\user\Readiness\LiquidityAndAccessToCapitalController::class);
    Route::resource('/CompetitivePosition-questions', \App\Http\Controllers\user\Readiness\CompetitivePositionController::class);
    Route::resource('/CustomerRecognition-questions', \App\Http\Controllers\user\Readiness\CustomerRecognitionController::class);
    Route::resource('/CustomerCommitment-questions', \App\Http\Controllers\user\Readiness\CustomerCommitmentController::class);
    Route::resource('/Affordable-questions', \App\Http\Controllers\user\Readiness\AffordableController::class);
    Route::resource('/IntellectualManagement-questions', \App\Http\Controllers\user\Readiness\IntellectualPropertyManagementController::class);
    Route::resource('/SaleForecast-questions', \App\Http\Controllers\user\Readiness\SaleForecastController::class);
    Route::resource('/UncertaintyPrediction-questions', \App\Http\Controllers\user\Readiness\UncertaintyPredictionController::class);
    Route::resource('/SupplyChain-questions', \App\Http\Controllers\user\Readiness\SupplyChainController::class);
    Route::resource('/Rule-questions', \App\Http\Controllers\user\Readiness\RuleController::class);

    Route::resource('/description-managerial', ManagerialController::class);
    Route::resource('/description-obtainedcertificates', ObtainedCertificateController::class);
    Route::resource('/description-planimplementations', PlanImplementationController::class);
    Route::resource('/description-technical', TechnicalController::class);
    Route::resource('/description-requiredcertificates',RequiredCertificateController::class);
    Route::resource('/description-market', DesMarketController::class);
    Route::resource('/product-supply-and-demands', ProductSupplyAndDemandController::class);
    Route::resource('/product-customers', ProductCustomerController::class);
    Route::resource('/raw-material-suppliers', RawMaterialSupplierController::class);
    Route::resource('/producers', ProducerController::class);
    Route::resource('/suppliers', SupplierController::class);
    Route::resource('/retails', RetailController::class);
    Route::resource('/environmental-effects', EnvironmentalEffectController::class);
    Route::resource('/product-competitors', ProductCompetitorController::class);
    Route::resource('/strengths', StrengthController::class);
    Route::resource('/weak-points', WeakPointController::class);
    Route::resource('/opportunity-points', OpportunityPointController::class);
    Route::resource('/threats', ThreatController::class);
    Route::resource('/alternative-products', AlternativeProductController::class);

    Route::get('/reporting/justification-plan', RepJustificationPlanController::class);

});

